# Generated by Django 6.0.2 on 2026-02-23 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('read', 'Read Article/Notes'), ('watch', 'Watched Video'), ('search', 'Searched Query'), ('quiz', 'Attempted Quiz')], max_length=20)),
                ('content_title', models.CharField(help_text='Title of the video, article, or search query', max_length=255)),
                ('content_text', models.TextField(help_text='The raw text, notes, or transcript for the AI to analyze')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_processed_by_ai', models.BooleanField(default=False, help_text='True if the NLP engine has already extracted concepts from this interaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
